### PR TITLE
Added to README: * [meteor-accounts-ciscospark]

### PR DESCRIPTION
**Pull request by levensailor**

### CODE REVIEW

**Review by levensailor — COMMENTED** [review]
following up on this PR

**Comment by ObjectIsAdvantag** [comment]
hi @levensailor, thanks for your contrib.
Could you add a license to your project, and enhance the formatting of the README, so that spark developers can get the benefit, may be a snapshot of the login via Meteor. 
Thanks

**Comment by ObjectIsAdvantag** [comment]
hi @levensailor , inquiry: are you planning to proceed and take the suggested changes mentionned above on your meteor contrib?

**Comment by ObjectIsAdvantag** [comment]
This PR is now 1 year+ old, closing
@levensailor let us know if you're still willing to push this contribution

**Pull request closed without merging**
