### PR TITLE
add pyIntegration

### PR DESCRIPTION
**Pull request by lorashley**
add resource for pyIntegration (flask/oauth sample)

### CODE REVIEW

**Comment by ObjectIsAdvantag** [comment]
hi @lorashley, this example is perfect, glad to see a python OAUTH sample joining the catalog.
I noticed though the project does not have a clear license. Could you add it so that the devs communities can safely reuse the contributed code. Feel free to reach to me on Webex teams if you need guidance on that part.

**Comment by lorashley** [comment]
i think im all set! @ObjectIsAdvantag  https://github.com/CiscoCollabTME/pyIntegration/blob/master/LICENSE

**Review by ObjectIsAdvantag — APPROVED** [review]
looks good

**Comment by ObjectIsAdvantag** [comment]
thanks @lorashley for your contrib!

**Pull request merged**
