### PR TITLE
Replace flint example

### PR DESCRIPTION
**Pull request by jpjpjp**
Replace flint example with webex-node-bot-framework sample

### CODE REVIEW

**Review by ObjectIsAdvantag — CHANGES_REQUESTED** [review]
thanks for your contribution,
please check:
1. there is an issue with the TOC in the PR, on line 23/25
2. in awesome, we don't typically replace but rather discuss adding a new resource and removing others, so please create separate issues for these 2 discussions

**Comment by jpjpjp** [comment]
This Webex Bot Starter is a direct replacement for the old Spark Bot Starter that is still using a brand we changed several years ago.  The functionality is essentially one for one, but the new sample uses correct branding and is based on a supported framework (as the original author of flint is no longer supporting it).

The change was discussed with the original author.   I leave it to the Awesome moderators to determine if its better to maintain old, poorly branded, no longer supported samples or to periodically refresh them over the years as the product moves.

**Comment by jpjpjp** [comment]
> thanks for your contribution,
> please check:
> 
>     1. there is an issue with the TOC in the PR, on line 23/25
> 
>     2. in awesome, we don't typically replace but rather discuss adding a new resource and removing others, so please create separate issues for these 2 discussions

Hi, based on the conversation in this issue: https://github.com/CiscoDevNet/awesome-webex/issues/83, perhaps we can pull the trigger on this?

**Comment by jpjpjp** [comment]
Hey @ObjectIsAdvantag, I noticed this morning that this PR never got completed.   As I mentioned I've checked in with the original owners of the flint project and the old sparkbot starter.   These are no longer maintained and they have blessed the replacements.     @nmarus and @valgaze, please feel free to let @ObjectIsAdvantag know if I'm misrepresenting anything here.

**Comment by valgaze** [comment]
@ObjectIsAdvantag @jpjpjp 

All sounds good, go for it

**Pull request closed without merging**
